import React from 'react'

function Inicio() {
  return (
    <div className='py-16 px-10'>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin interdum leo eget mollis dignissim. Donec varius a leo eu porta. Duis et nisl sit amet lorem feugiat mattis sed vitae metus. Morbi sit amet congue dui. Maecenas volutpat diam vitae tortor maximus euismod. Morbi maximus tristique libero quis luctus. Etiam sed orci ut magna imperdiet porttitor a ut dolor. Sed ultrices ante a nibh egestas bibendum.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vulputate nibh et volutpat sodales. Aliquam ac malesuada mi. Phasellus mattis, dui vitae ornare sollicitudin, eros justo eleifend metus, nec placerat mi nisi sed purus. Quisque est arcu, mollis sit amet porttitor ac, vehicula in nunc. Nam urna leo, pretium id est ut, lobortis rutrum enim. Nam pellentesque pretium finibus. Suspendisse sed neque maximus dolor dapibus pharetra quis eget leo. Vestibulum ullamcorper finibus purus, et malesuada dolor mollis nec. Fusce non velit massa. Proin aliquam velit ut metus suscipit ultricies. Nullam aliquet et metus eu scelerisque. Nulla facilisi. Duis consequat ex nec ultrices tristique. Mauris maximus lacus malesuada mauris interdum finibus. Fusce eu faucibus elit, ut egestas elit.</p>
      <p>Donec tristique mi et eros placerat suscipit vel vel orci. Sed ornare mollis elit ac ultricies. Vestibulum eget dolor id sem euismod malesuada. Donec suscipit non nisi ac varius. Nulla elementum, elit nec ultrices scelerisque, sem odio consequat odio, gravida maximus lectus metus vitae diam. Mauris porttitor, nibh condimentum suscipit dignissim, est tellus fringilla odio, a luctus nisi justo at erat. Cras dignissim nisl elementum molestie luctus. Morbi ullamcorper faucibus sapien eu dapibus. Nunc elementum orci nunc, in vestibulum dui cursus nec. Nam vulputate laoreet sapien semper interdum. Nulla semper luctus justo non porta. Fusce eleifend lectus vitae augue molestie, at rutrum orci blandit. Nulla ut mi id mauris molestie semper. Vivamus a sollicitudin elit.</p>
      <p>Donec tristique mi et eros placerat suscipit vel vel orci. Sed ornare mollis elit ac ultricies. Vestibulum eget dolor id sem euismod malesuada. Donec suscipit non nisi ac varius. Nulla elementum, elit nec ultrices scelerisque, sem odio consequat odio, gravida maximus lectus metus vitae diam. Mauris porttitor, nibh condimentum suscipit dignissim, est tellus fringilla odio, a luctus nisi justo at erat. Cras dignissim nisl elementum molestie luctus. Morbi ullamcorper faucibus sapien eu dapibus. Nunc elementum orci nunc, in vestibulum dui cursus nec. Nam vulputate laoreet sapien semper interdum. Nulla semper luctus justo non porta. Fusce eleifend lectus vitae augue molestie, at rutrum orci blandit. Nulla ut mi id mauris molestie semper. Vivamus a sollicitudin elit.</p>
      <p>Donec tristique mi et eros placerat suscipit vel vel orci. Sed ornare mollis elit ac ultricies. Vestibulum eget dolor id sem euismod malesuada. Donec suscipit non nisi ac varius. Nulla elementum, elit nec ultrices scelerisque, sem odio consequat odio, gravida maximus lectus metus vitae diam. Mauris porttitor, nibh condimentum suscipit dignissim, est tellus fringilla odio, a luctus nisi justo at erat. Cras dignissim nisl elementum molestie luctus. Morbi ullamcorper faucibus sapien eu dapibus. Nunc elementum orci nunc, in vestibulum dui cursus nec. Nam vulputate laoreet sapien semper interdum. Nulla semper luctus justo non porta. Fusce eleifend lectus vitae augue molestie, at rutrum orci blandit. Nulla ut mi id mauris molestie semper. Vivamus a sollicitudin elit.</p>
    </div>
  )
}

export default Inicio
